### ISSUE TITLE
可移动的UI面板问题

### ISSUE THREAD

**Issue by MeliodasZHAO** [nyxkrage/st-discord-inspired#1]
UI面板的移动只改变窗口大小，文本框和输入框的位置不随移动而改变
![image](https://github.com/nyxkrage/st-discord-inspired/assets/150231855/5581b9da-ec3b-468b-b7b1-d12f422a3662)
![image](https://github.com/nyxkrage/st-discord-inspired/assets/150231855/107b6228-a3d9-4db0-9107-d8598ff040cc)

**Comment by nyxkrage** [comment]
MovingUI is not supported with this theme
